version: "3"

services:
  backend:
    image: suryasuraj/notes-server:latest
    container_name: notes-server-con
    ports:
      - "7000:7000"
    networks:
      - notes-network

  frontend:
    image: suryasuraj/notes-client:latest
    container_name: notes-client-con
    ports:
      - "5173:5173"
    networks:
      - notes-network
    
networks:
  notes-network:

