kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: note-app-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.31.2
  - role: worker
    image: kindest/node:v1.31.2
  - role: worker
    image: kindest/node:v1.31.2    
    extraPortMappings:
      - containerPort: 31000 # as we did in the service for frontend
        hostPort: 5173
        protocol: TCP
      - containerPort: 31001   # as we did in the service for frontend
        hostPort: 7000
        protocol: TCP
