kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: note-app-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.31.2
  - role: worker
    image: kindest/node:v1.31.2
    extraPortMappings:
      - containerPort: 5173
        hostPort: 5173
        protocol: TCP
      - containerPort: 7000
        hostPort: 7000
        protocol: TCP
